FROM tokarevart/neper

RUN apt-get update && apt-get install curl && \ 
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

ENV PATH="/root/.cargo/bin:${PATH}"

RUN cargo install --git https://github.com/tokarevart/polyqd.git

WORKDIR /home
