FROM tokarevart/gmsh

RUN apt-get update && apt-get -y install \
	build-essential \
	git \
	libgsl-dev \
	libnlopt-dev \
	libscotch-dev \
	libpthread-stubs0-dev \
	cmake

RUN git clone https://github.com/rquey/neper.git && \
	cd /neper && \
	cmake /neper/src/ && \
	make -j "$(nproc)" && \
	make install
